/*
 Project Euler Problem 2
 =======================

 Each new term in the Fibonacci sequence is generated by adding the
 previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 Find the sum of all the even-valued terms in the sequence which do not
 exceed four million.
 */
var program = main();
function main(){
	var sum = 0, f = 0;
	for(var i =0; (f = fib(i)) <=4000000; i++){
		
    if(f % 2 == 0){
			sum+=f;
		} 
	}
	console.log(sum);
}
function fib(term){
	var term1 = 0;
	var term2 = 1;
	if(term == 1 || term ==2){
		return term1+term2;
	}
	for(var i = 0; i < term; i++){
		var temp = term1;
		term1 = term1 +term2;
		term2 = temp;
	}
	return term1;
}
