import java.util.Date;
/*
Project Euler Problem 45
========================

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle     T[n]=n(n+1)/2   1, 3, 6, 10, 15, ...
Pentagonal   P[n]=n(3n-1)/2  1, 5, 12, 22, 35, ...
Hexagonal    H[n]=n(2n-1)    1, 6, 15, 28, 45, ...

It can be verified that T[285] = P[165] = H[143] = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

public class Euler045 {
    public static void main(String[] args) {
        Date start, end;
        start = new Date();
        for(int i = 144;;i++){
        	int l = hexagonal(i);
        	if(isPentagonal(l) && isTriangle(l)){
        		System.out.println(l);
        		break;
        	}
        }
        end = new Date();
        System.out.println("Execution Time: " + (end.getTime() -start.getTime()));
    }
    public static boolean isPentagonal(double p){
    	
    	return isInteger((1+ Math.sqrt(1+24*p))/6) ;
    }
    public static boolean isTriangle(double p){
    	return isInteger((1+Math.sqrt(1+8*p))/2);
    }
    public static boolean isInteger(double p){
    	return p == Math.floor(p);
    }
	public static int hexagonal(int n) {
		return n * (2 * n - 1);
	}

}
